/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as DashboardHomeRouteImport } from './routes/_dashboard/home'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicProjectsRouteRouteImport } from './routes/_public/projects/route'
import { Route as PublicSkillsRouteImport } from './routes/_public/skills'
import { Route as DashboardAuthIndexRouteImport } from './routes/_dashboard/auth/index'
import { Route as PublicProjectsIndexRouteImport } from './routes/_public/projects/index'
import { Route as PublicProjectsSplatRouteImport } from './routes/_public/projects/$'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/_dashboard/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicProjectsRouteRoute = PublicProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSkillsRoute = PublicSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardAuthIndexRoute = DashboardAuthIndexRouteImport.update({
  id: '/_dashboard/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicProjectsRouteRoute,
} as any)
const PublicProjectsSplatRoute = PublicProjectsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicProjectsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/coming-soon': typeof ComingSoonRoute
  '/projects': typeof PublicProjectsRouteRouteWithChildren
  '/home': typeof DashboardHomeRoute
  '/skills': typeof PublicSkillsRoute
  '/projects/$': typeof PublicProjectsSplatRoute
  '/auth/': typeof DashboardAuthIndexRoute
  '/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/coming-soon': typeof ComingSoonRoute
  '/home': typeof DashboardHomeRoute
  '/skills': typeof PublicSkillsRoute
  '/': typeof PublicIndexRoute
  '/projects/$': typeof PublicProjectsSplatRoute
  '/auth': typeof DashboardAuthIndexRoute
  '/projects': typeof PublicProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/coming-soon': typeof ComingSoonRoute
  '/_public/projects': typeof PublicProjectsRouteRouteWithChildren
  '/_dashboard/home': typeof DashboardHomeRoute
  '/_public/skills': typeof PublicSkillsRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/projects/$': typeof PublicProjectsSplatRoute
  '/_dashboard/auth/': typeof DashboardAuthIndexRoute
  '/_public/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coming-soon'
    | '/projects'
    | '/home'
    | '/skills'
    | '/projects/$'
    | '/auth/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/coming-soon'
    | '/home'
    | '/skills'
    | '/'
    | '/projects/$'
    | '/auth'
    | '/projects'
  id:
    | '__root__'
    | '/_public'
    | '/coming-soon'
    | '/_public/projects'
    | '/_dashboard/home'
    | '/_public/skills'
    | '/_public/'
    | '/_public/projects/$'
    | '/_dashboard/auth/'
    | '/_public/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ComingSoonRoute: typeof ComingSoonRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardAuthIndexRoute: typeof DashboardAuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/home': {
      id: '/_dashboard/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/projects': {
      id: '/_public/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PublicProjectsRouteRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/skills': {
      id: '/_public/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof PublicSkillsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_dashboard/auth/': {
      id: '/_dashboard/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof DashboardAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/projects/': {
      id: '/_public/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicProjectsRouteRoute
    }
    '/_public/projects/$': {
      id: '/_public/projects/$'
      path: '/$'
      fullPath: '/projects/$'
      preLoaderRoute: typeof PublicProjectsSplatRouteImport
      parentRoute: typeof PublicProjectsRouteRoute
    }
  }
}

interface PublicProjectsRouteRouteChildren {
  PublicProjectsSplatRoute: typeof PublicProjectsSplatRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
}

const PublicProjectsRouteRouteChildren: PublicProjectsRouteRouteChildren = {
  PublicProjectsSplatRoute: PublicProjectsSplatRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
}

const PublicProjectsRouteRouteWithChildren =
  PublicProjectsRouteRoute._addFileChildren(PublicProjectsRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicProjectsRouteRoute: typeof PublicProjectsRouteRouteWithChildren
  PublicSkillsRoute: typeof PublicSkillsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicProjectsRouteRoute: PublicProjectsRouteRouteWithChildren,
  PublicSkillsRoute: PublicSkillsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ComingSoonRoute: ComingSoonRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardAuthIndexRoute: DashboardAuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
